### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by renmengjie7** [bigcode-project/starcoder2-self-align#12]
I use `python install -e .` to build environment and run eval, but encounter the following warning.
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

And I found even use the infer results in the repository, the execution result of cases about **`numpy`** is different from the repository.
In my environment, `numpy==2.1.2`

Have I missed anything? Do you have any insights or suggestions?

**Comment by renmengjie7** [comment]
when I use `numpy==1.26.4`, there is no problem.

But I still want to know the version used in the repository.

**Comment by UniverseFly** [comment]
Hi, `numpy` 2.0 introduced many backward incompatible changes ([link](https://numpy.org/doc/stable/numpy_2_0_migration_guide.html)). We use `1.26.4`.
