### ISSUE TITLE
Inquiry about Accessing the NIPS 2024 Paper

### ISSUE THREAD

**Issue by brick-pid** [bigcode-project/starcoder2-self-align#13]
Hello,

I am looking for the paper you presented at NIPS 2024, but I couldn’t find it on arXiv. I am very interested in your research and would like to read it in detail, as well as cite your work in my own paper.

Thank you for your help!

**Comment by UniverseFly** [comment]
Hi, thanks for your interest in our work 🙂. It was just online yesterday and you can find it here: https://arxiv.org/abs/2410.24198.
