### ISSUE TITLE
can you release the snippet->concept data?

### ISSUE THREAD

**Issue by huu4ontocord** [bigcode-project/starcoder2-self-align#7]
Hi - can you release on HF the concepts for each of the snippets?

Thank you!

**Comment by UniverseFly** [comment]
Yes, I think @cassanof can help with this.

**Comment by cassanof** [comment]
> Hi - can you release on HF the concepts for each of the snippets?
> 
> Thank you!

Hey! We just released every single step of the dataset pipeline. Scroll at the bottom of the model card and you will find each dataset for each step:  https://huggingface.co/bigcode/starcoder2-15b-instruct-v0.1
